- name: Test & publish code coverage
  uses: paambaati/codeclimate-action@v5.0.0
  env:
      CC_TEST_REPORTER_ID: <code_climate_reporter_id>
  with:
    coverageCommand: npm run coverage
      debug: true
